### ISSUE TITLE
LS-X1.0TL

### ISSUE THREAD

**Issue by bcoff12** [1000001101000/Debian_on_Buffalo#36] opened 2020-02-25 15:42 UTC
I know this is a longshot, but I was curious if there was a way to install Debian to the subject device?  It has no USB / power switch but it would be a lot more useful running Debian than the stock firmware.

Thanks!

**Comment by 1000001101000** [comment] 2020-02-25 19:18
Good to hear from you!

It should be possible but I believe we'll need to create a new device-tree for it and will probably need to go through some trial and error to get it working. 

The first step is to confirm some details about the hardware it's running. 

There's an old page out there with some hardware details but I'd like to confirm them first:
https://web.archive.org/web/20180319150521/http://buffalo.nas-central.org/wiki/Category:LS-XL

You should be able to get most of what we need by connecting using ACP_commander and posting the output of "dmesg" 
https://github.com/1000001101000/acp-commander

Once we have that hardware information I'll build a device tree and we can try booting into an installer image with it. This may take a few tries which may require connecting the drive to a PC (or TFTP I suppose) to recover. Before we start you should confirm you're able to access the drive without too much trouble.

**Comment by bcoff12** [comment] 2020-02-25 20:04
I have it in pieces and can easily test.

I restored the original image and booted it.

Output from dmesg and /var/log/messages here:

https://pastebin.com/F9ngexDb

**Comment by 1000001101000** [comment] 2020-02-25 21:02
excellent, that confirms most of my assumptions. I'll take a shot at a device tree tonight and we can give it a shot. 

For the first one I won't include any LEDs or Buttons to avoid pin conflicts. Assuming we get that working you can then run through the Debian install like normal. Once we get you running Debian I'd like to do some tests to verify various hardware components and then I can walk you through how I map LEDs and Buttons.

**Comment by bcoff12** [comment] 2020-02-25 21:11
Thank you so much.

I have SSH access working if you need anything else.  I will provide anything needed to get this working.

**Comment by 1000001101000** [comment] 2020-02-25 21:18
could you post the output of "find /proc/buffalo"? I think that will give us somethings we'll need later like a list of the leds

**Comment by 1000001101000** [comment] 2020-02-25 21:18
also "ls /sys/block"

**Comment by 1000001101000** [comment] 2020-02-25 21:22
just to be thorough:
"cat /proc/cpu"
"ls -lh /boot"
and if this works:
"hexdump -C /dev/mtdblock0 | grep -i uimage" 
"hexdump -C /dev/mtdblock1 | grep -i uimage"

**Comment by bcoff12** [comment] 2020-02-25 22:24
Please see:

https://pastebin.com/SusKknFV

**Comment by 1000001101000** [comment] 2020-02-25 22:38
perfect. I created a super-basic device tree and added it to the project along with a flash-kernel entry that should allow an install to succeed. New installer images have been generated which incorporate these files:

https://github.com/1000001101000/Debian_on_Buffalo/tree/master/Buster/installer_images/armel_devices

Give it a try and see what happens. With a little luck it should boot straight into the installer. If not we can troubleshoot as needed.

**Comment by bcoff12** [comment] 2020-02-25 23:46
Ok, copied the files to /boot and rebooted.  It hasn't pulled an IP address after several minutes.  I am remote from the device so I will check it in the morning.  Thanks again!

**Comment by 1000001101000** [comment] 2020-02-25 23:50
Sounds good. 

Hopefully it’s just an issue with the network (I only enabled 1 of 2 possible adapters). If it’s boot looping it may be something more subtle.

**Comment by bcoff12** [comment] 2020-02-26 13:26
It was in a boot loop.

Is anything logged that I can look at?  I have the drive pulled and mounted on another system.

**Comment by 1000001101000** [comment] 2020-02-26 14:30
until we get past the boot loop stage there won't be any debug info we can look at without attaching a serial console. If you are good at soldering (I'm not) that page I sent you showed how to connect via a 3.3v usb adapter. 

I'll look over the device tree again and see if I can find something that could be causing the issue. I based it off a different device that uses the same SoC but a couple of things didn't match what I'm used to for other SoCs. I'll take a look at a few others and see if there's something that needs fixing. 

The main thing you can check on your end is that files on the disk show as valid. If you connect to a linux system and use the "file" command they should show as uboot images along with some details, if not they may not have downloaded correctly..... now that I mention that, I need to verify I built the uImage properly too. I added it to the build process I'm using for the other Kirkwood devices assuming the entry point would be the same but should verify that too.

**Comment by bcoff12** [comment] 2020-02-26 14:44
Files confirmed valid.

Those solder points are tiny!  I can give that a shot if it comes to that.

**Comment by 1000001101000** [comment] 2020-02-26 16:43
Hopefully it won't come to that. 

I started over based off the "Marvell RD88F6192 reference design" which is probably what I should have started with. There was one difference in how the console was set up which I wouldn't think would make a difference but if it was causing a problem it would explain the boot loop. 

give that one a try and see what happens. 

I've got a handful of things we can try until something works but are largely stuck with trial and error for now.

**Comment by bcoff12** [comment] 2020-02-26 18:12
Reboot loop.

**Comment by 1000001101000** [comment] 2020-02-26 18:30
I Just posted another one. this one is basically the lswxl one with the memory value adjusted. 

If that doesn't help I'm going to try again based on the reference design but with the Stretch kernel to narrow some some possibilities. I'll take a look at the stock kernel source at some point to see if I can find any hints.

**Comment by bcoff12** [comment] 2020-02-26 19:14
Thanks again for your efforts.

This one also went into a reboot loop.

**Comment by 1000001101000** [comment] 2020-02-26 19:17
could you take a picture of the board when you get a chance?

I'd particularly like to see the SoC, it'll be the biggest chip and should say 88f6190 or something similar.

I've got a few more things to try yet, but the serial console is looking more and more tempting.

**Comment by bcoff12** [comment] 2020-02-26 19:22
I can take a photo if you need.
88F6-LG02
N4W8590.2
1132 A1P
TW
88F6192-A1
C080

**Comment by 1000001101000** [comment] 2020-02-26 19:33
That should give me what I need to confirm the SoC stuff. A picture would help later on so I can match chips to the device tree but most of that comes later. 

I took a peek at the stock firmware. it looks like they use the same kernel for all the kirkwood linkstation devices. That would make me assume this shouldn't be so difficult but there may be a reason this one didn't get supported along with the other devices. I guess we'll find out.

**Comment by bcoff12** [comment] 2020-02-26 19:35
Would the low RAM have anything to do with that?

**Comment by 1000001101000** [comment] 2020-02-26 19:37
If read everything correctly this device should have 64MB ram. The older Orion-based Linkstations have the same and work just fine. I wouldn't think it's an issue.

**Comment by 1000001101000** [comment] 2020-02-26 19:39
I posted another one (the build process should run in a few minutes to update the installer). This one strips it down to the absolute minimum to boot (including removing ethernet and sata). That should narrow things down further.

**Comment by bcoff12** [comment] 2020-02-26 19:51
Sorry to report that this one also resulted in a reboot loop.

**Comment by 1000001101000** [comment] 2020-02-26 19:53
not surprising but it confirms it at least.

**Comment by 1000001101000** [comment] 2020-02-26 19:56
I found something interesting. Looks like someone created a kernel patch to boot this device a while back:
https://forum.doozan.com/read.php?2,15699
https://github.com/ingmar-k/Buffalo-Linkstation-Kirkwood-Kernel/commit/3bc4ecb73f668e7fdb191427492ac079b390118f

This is the "old" way of doing things from before device trees and wouldn't work as-is on a modern kernel but should be helpful in figuring things out.

**Comment by 1000001101000** [comment] 2020-02-26 20:00
here's something else you can try in the meantime:

try the lschlv2 image from my repo. if that doesn't work either try this one:
http://ftp.debian.org/debian/dists/stretch/main/installer-armel/current/images/kirkwood/network-console/buffalo/ls-chlv2/

**Comment by bcoff12** [comment] 2020-02-26 20:15
lschlv2 - reboot loop.

Second one - boot successfully, allows connection on SSH, and I can login with installer/install.

**Comment by 1000001101000** [comment] 2020-02-26 20:28
that's more like it. 

I'm guessing this means it doesn't like the kernel I'm using for the buster installer. Could you try this one next:

http://ftp.nl.debian.org/debian/dists/buster/main/installer-armel/current/images/kirkwood/network-console/buffalo/ls-chlv2/

**Comment by bcoff12** [comment] 2020-02-26 21:14
This one also boots successfully and allows me to login with installer/install.

**Comment by 1000001101000** [comment] 2020-02-26 21:25
Excellent. 

The problem seems to be with the kernel I use for the Buster installer. I'm using a custom kernel because the Terastation II and Terastation III require custom patches to work. This hasn't been a problem for the other kirkwood devices but apparently is for the ls-xl for some reason. 

Eventually I would like to get it working with my kernel but I think we should start by getting a good device-tree for the ls-xl on the current Buster kenel provided by debian and expand from there. 

Try running through the install with that last image and see how far you get. It'll be easier to work on the device tree from a functioning install if you can get that far. If that works it'll be fairly simple to adjust the device tree to handle the ls-xl hardware properly.

**Comment by bcoff12** [comment] 2020-02-26 21:27
Will do.  I can't thank you enough.

**Comment by 1000001101000** [comment] 2020-02-26 21:43
looks like I am using a different entry point in my uImages 0x00008000 vs 0x01A00000 compared to the ones provided by Debian. 

If that mattered for other devices I should have seen failures when testing the ls-wxl at the very least.  Makes me think it isn't the issue, but I think I'll test with some other devices at some point. 

We'll find out for sure when we start testing new trees later on.

**Comment by bcoff12** [comment] 2020-02-27 12:53
I had issues with my session being disconnected during the install - on my last attempt, I got as far as "determining kernel version" before it died.  The disconnections didn't seem to occur at the same step in the process, so I don't think it was a specific action that caused it. 

I'm going to restore a bootable disk and try one more time and I'll let you know.

**Comment by 1000001101000** [comment] 2020-02-27 13:12
Interesting.

Since we’re using a device tree for another device some instability isn’t too surprising.

I’ll try packaging up the installer/kernel that we know works with a device-tree based on our earlier attempts. Hopefully that will work better

**Comment by 1000001101000** [comment] 2020-02-27 17:22
I setup a new workflow to create a "kirkwood" installer that uses the default Debian kernel rather than my custom one (basically the same process I use for ARMHF). I'm thinking of making this change permanent to avoid weird issues like this for devices that don't actually need the custom kernel. 

since it uses the same kernel that you've already had success with I expect we'll have better luck. Hopefully switching to a tree meant for the 88F6192 and without entries for non-existant hardware the instability will go away. I've set up the workflow to trigger whenever I push a new dtb, hopefully that will help us iterate faster too.
 
the new images can be found under:
Buster/installer_images/armel_devices/kwtest/

**Comment by bcoff12** [comment] 2020-02-27 17:31
Thank you, I will try it.

I had some issues restoring my Clonezilla image this morning but that's all taken care of.

I just tried with the ftp.nl.debian.org again and it disconnected when I was setting up the user account.

**Comment by 1000001101000** [comment] 2020-02-27 17:47
the lschlv2 device tree defines a bunch of hardware (buttons/fans/leds/etc) that the ls-xl doesn't have. If the ls-xl uses those same pins for something important it could be causing an issue. I imagine there  could be some more subtle issues with using a device tree meant for a different SoC too, though looking at how there aren't many relevant differences (which explains why it works at all). 

It could also be something we're missing like setting up a watchdog timer or something of that nature. 

fortunately, some of these issues can be seen from a second window you could watch during the install though many would still fail to quickly to make it out over ssh.

**Comment by bcoff12** [comment] 2020-02-27 17:53
KWTEST - reboot loop.

I will try with two windows open and ftp.nl.debian.org and let you know.

**Comment by 1000001101000** [comment] 2020-02-27 18:11
usually if you connect in the seperate window and then choose exit in the menu it will fall to a screen showing the output of syslog in realtime. Depending on what's happening this may give useful info. 

I think for the next device tree I'll start with the working-ish ls-chlv2 tree and pull out some things that shouldn't be there for the ls-xl. starting with something that boots is probably a better starting point.

**Comment by bcoff12** [comment] 2020-02-27 19:59
Ok I am probably spending too much time making this perfect, but I think adding a swap partition and doing a swapon is helping me with my issue....  I will quit trying to get my partition table just right and just get an install completed and let you know!

**Comment by 1000001101000** [comment] 2020-02-27 20:12
yes.... 100% that. I hadn't thought of that but a 64MB device will have problems without swap. 

I'm hoping we'll get my custom installer working eventually because there is an additional tweak that I make specifically for systems with <128M to prevent some systemd stuff from failing. It shouldn't be a big deal for your initial install though.

**Comment by bcoff12** [comment] 2020-02-28 13:19
Install is proceeding - slowly.

**Comment by 1000001101000** [comment] 2020-02-28 14:53
The speed will be limited by a number of factors, particularly since it pulls all the packages from a Debian mirror. If it's taking more than an hour or hanging in one place I would be somewhat concerned. 

I know I had to make some tweaks to the installer to make certain things work on the ls-gl which also only has 64mb ram. I believe the only one during the install was trying to compress the initramfs using xz, the other issue was systemd services failing at start. 

The code I use is (run from inside the target environment):
echo "tmpfs /run tmpfs nosuid,noexec,size=26M,nr_inodes=4096 0  0" >> /etc/fstab
mount -o remount tmpfs

If it's getting stuck right around installing the kernel it could be a similar issue and this could help.

**Comment by 1000001101000** [comment] 2020-02-28 17:50
Let me know how the install turns out. I think I have an ls-chlv2, if so I'm going to pull it out and do some parellel testing. Hopefully that way I can confirm that images I post work before sending them to you.... or at least confirm whether some of these issues are ls-xl specific.

**Comment by bcoff12** [comment] 2020-02-28 18:37
Will do.  The install is proceeding, but it is VERY slow.  I can only guess that it is doing a ton of swapping - "free" shows swap in use but I can't tell how much swapping it is actually doing.  I just don't have any other explanation for why it is taking so long.

**Comment by 1000001101000** [comment] 2020-02-28 18:50
depending on how slow that drive is swapping and all the writes involved in downloading and unpacking all the packages could be very slow. I've never seen one go anything like this long but I've only done a few on devices with 64MB ram and I think those were mostly with some cheap SSDs I use for testing.

Probably best to leave it alone and see if if it finishes though it's probably worth opening another session and take a look at the output of dmesg to see if something is spewing out warning/errors.

I'll have to see how it goes on the ls-chlv2 when I get that far. It has the same amount of ram and a slower clock speed which should make an interesting comparison.

**Comment by bcoff12** [comment] 2020-02-28 19:36
dmesg - clean.  Nothing in it since it mounted the target / partition.

**Comment by 1000001101000** [comment] 2020-02-28 19:37
what step is it on right now, is it still installing packages?

**Comment by bcoff12** [comment] 2020-02-28 19:44
Correct...  16%.

**Comment by 1000001101000** [comment] 2020-02-28 19:52
may as well let it run since you've come this far.

how fast is your internet connection?

**Comment by bcoff12** [comment] 2020-02-28 19:58
Not this slow!  LS210 took under an hour as comparison.  This install looks slightly different but I'm pretty sure it is the combination of the hardware and the old rotational disk I'm testing with.

**Comment by 1000001101000** [comment] 2020-02-28 20:21
I wouldn't expect it to take more than 2-3x as long based of CPU/memory alone. I'm sure we can  eventually figure out whatever the issue is. If the install succeeds we'll have a lot more tools to work with. 

If the last few steps fail (the screen will turn red), don't turn it off/reboot. we can probably correct most issues manually and allow the install to finish.

**Comment by 1000001101000** [comment] 2020-02-28 20:23
how much swap did you give it?

**Comment by bcoff12** [comment] 2020-02-28 20:48
Currently "Preparing the system" (window title "Making the system bootable"

1GB swap.

**Comment by 1000001101000** [comment] 2020-02-28 21:08
fingers crossed

**Comment by bcoff12** [comment] 2020-02-28 21:22
Wish I had used an SSD!!

**Comment by 1000001101000** [comment] 2020-02-28 21:40
if this does turn out to be because of the drive I would suspect it's failing. 

I'd love to blame it on 88F6192 vs 88F6281 device tree issues but looking closer, the only differences appear to be related to the SoC on-board sdcard port which isn't even enabled in the device-tree. I suppose it could be some sort of conflict caused by have the fan/buttons defined even though they don't exist but I don't really see how. 

Hopefully your install will finish soon and you can take a look at the SMART data.

**Comment by bcoff12** [comment] 2020-02-28 22:56
It may be.  It is a 1.5TB drive and who knows what its history is...

It is still running.  I am working at 6AM EST tomorrow so I can let it go overnight and check it in the AM.

**Comment by 1000001101000** [comment] 2020-02-29 14:26
I set up my ls-chlv2 with an existing Debian Stretch image (what I had handy). I’ve got it running with a stripped down dtb which i’m modifying to try to match ls-xl hardware. Once ai get that relatively clean I’ll modify it for buster and do some installer testing

**Comment by bcoff12** [comment] 2020-02-29 18:39
I have a booted image but I can't remember the user/pass!!!  I have it written down so I won't be able to get on it until tomorrow.

**Comment by bcoff12** [comment] 2020-03-01 14:21
Ok, I was using the right user/pass.

It had gone through a full install, and at the end said it was ready to boot into the new OS, and instead it booted back into the installer environment! 

I am remote from the disk - is there anything of value I can get by pulling the drive and mounting it in a separate system?  I can do that but it will either be later today or tomorrow.

**Comment by 1000001101000** [comment] 2020-03-01 15:54
That generally means that you didn’t specify sda1 as /boot. For the device to boot into the new system the *.buffalo files are replaced with new ones generated by the installer.

This can be recovered remotely (I’ve done it a lot during testing. I’ll post the steps once I get in front of a better keyboard.

**Comment by 1000001101000** [comment] 2020-03-01 19:30
Alright, the goal is to use the installer environment to access the install you just created and adjust it to use sda1 as /boot and then generate new boot files.

1. Connect to the installer and run through till the partitioning menu (needed to load disk drivers)

2. In another menu and start a shell and run the following:
mount <rootfs partition> /mnt
mount /dev/sda1 /mnt/boot
mount -o bind /dev /mnt/dev
mount -t proc none /mnt/proc
mount -t sysfs none /mnt/sys
chroot /mnt /bin/bash
update-initramfs -u

### it should then generate new boot files in /boot

exit
Reboot

it should then boot into the system. To finish you’ll want to create an fstab entry for /boot and test it.

**Comment by bcoff12** [comment] 2020-03-01 21:23
~ # mount /mnt
mount: can't find /mnt in /etc/fstab

Sorry I should be able to understand what you want here but I'm not certain.

The other mount commands work if I pre-populate /mnt with the target directories.

**Comment by bcoff12** [comment] 2020-03-01 21:24
SCSI1 (0,0,0) (sda) - 1.5 TB ATA ST31500341AS           ↑        │
  │        >             1.0 MB       FREE SPACE                   ▮        │
  │        >     #1      1.0 GB       ext3        primary          ▒        │
  │        >     #2      5.1 GB       ext3        primary          ▒        │
  │        >     #3      1.0 GB    F  swap                 swap    ▒        │
  │        >     #4    993.1 GB       ext4                         ▒        │
  │        >           500.1 GB       FREE SPACE                   ▒        │
  │                                                                ▒        │
  │        Undo changes to partitions                              ↓

**Comment by bcoff12** [comment] 2020-03-01 21:25
#1 - boot
#2 - original / from Buffalo
#3 - Swap
#4 - where I installed

**Comment by 1000001101000** [comment] 2020-03-01 21:39
Sorry, the rest of that mount command was eaten by markup language, I adjusted it above.

should be mount /dev/sda4 /mnt

**Comment by bcoff12** [comment] 2020-03-01 22:03
Do I need to update fstab before I reboot???

**Comment by 1000001101000** [comment] 2020-03-01 22:05
No, you’ll need to before you can update the kernel or make other changes. I find it’s better to get it booting first then setup the fstab entry from Debian where you can test the fstab entry more easily

**Comment by bcoff12** [comment] 2020-03-01 22:51
Ok, there is a /boot on /dev/sda4:

drwxr-xr-x   18 root     root          4096 Mar  1 22:07 ..
drwxr-xr-x    3 root     root          4096 Feb 28 23:18 .
-rw-r--r--    1 root     root         12227 Feb 28 23:18 dtb
-rw-r--r--    1 root     root       5696654 Feb 28 23:18 initrd.buffalo
-rw-r--r--    1 root     root       2060867 Feb 28 23:18 uImage.buffalo
lrwxrwxrwx    1 root     root            44 Feb 28 23:18 dtb-4.19.0-8-marvell -> dtbs/4.19.0-8-marvell/./kirkwood-lschlv2.dtb
lrwxrwxrwx    1 root     root            44 Feb 28 23:18 dtb.bak -> dtbs/4.19.0-8-marvell/./kirkwood-lschlv2.dtb
drwxr-xr-x    3 root     root          4096 Feb 28 23:18 dtbs
-rw-r--r--    1 root     root       5696590 Feb 28 23:17 initrd.img-4.19.0-8-marvell
lrwxrwxrwx    1 root     root            27 Feb 28 02:23 initrd.img -> initrd.img-4.19.0-8-marvell
lrwxrwxrwx    1 root     root            27 Feb 28 02:23 initrd.img.old -> initrd.img-4.19.0-8-marvell
lrwxrwxrwx    1 root     root            24 Feb 28 02:23 vmlinuz -> vmlinuz-4.19.0-8-marvell
lrwxrwxrwx    1 root     root            24 Feb 28 02:23 vmlinuz.old -> vmlinuz-4.19.0-8-marvell
-rw-r--r--    1 root     root       1643741 Jan 26 20:01 System.map-4.19.0-8-marvell
-rw-r--r--    1 root     root        169818 Jan 26 20:01 config-4.19.0-8-marvell
-rw-r--r--    1 root     root       2048576 Jan 26 20:01 vmlinuz-4.19.0-8-marvell


And when I mount /dev/sda1 into /mnt/boot, it appears to be the installer files.

drwxr-xr-x 18 root root     4096 Mar  1 17:07 ..
drwxr-xr-x  5 root root     4096 Feb 27 15:20 .
-rwxr-xr-x  1 root root 12474606 Feb 27 15:20 initrd.buffalo
-rw-r--r--  1 root root  2060867 Feb 27 15:20 uImage.buffalo
drwxr-xr-x  2 root root     4096 Feb 27 15:20 ftp.nl.debian.org
drwxr-xr-x  2 root root     4096 Feb 27 15:19 ORIG
-rw-r--r--  1 root root     8569 Feb 27 10:53 conf_save.md5sum
-rw-r--r--  1 root root   157767 Feb 27 10:53 log.tgz
-rw-r--r--  1 root root    65629 Feb 27 10:53 conf_save.tgz
-rw-r--r--  1 root root  2664224 Jun 30  2015 uImage.buffalo.org
drwx------  2 root root    16384 Mar 27  2012 lost+found

Your instructions completed without error but it rebooted back into the installer.

**Comment by bcoff12** [comment] 2020-03-01 23:03
If I follow your instructions but DO NOT mount /dev/sdb1 into /mnt/boot...  /boot contains this:

drwxr-xr-x  3 root root    4096 Mar  1 18:02 .
-rw-r--r--  1 root root   12227 Mar  1 18:02 dtb
-rw-r--r--  1 root root 5696656 Mar  1 18:02 initrd.buffalo
-rw-r--r--  1 root root 2060867 Mar  1 18:02 uImage.buffalo
lrwxrwxrwx  1 root root      44 Mar  1 18:02 dtb.bak -> dtbs/4.19.0-8-marvell/./kirkwood-lschlv2.dtb
lrwxrwxrwx  1 root root      44 Mar  1 18:02 dtb-4.19.0-8-marvell -> dtbs/4.19.0-8-marvell/./kirkwood-lschlv2.dtb
-rw-r--r--  1 root root 5696592 Mar  1 18:02 initrd.img-4.19.0-8-marvell
drwxr-xr-x 18 root root    4096 Mar  1 17:07 ..
-rw-r--r--  1 root root 5696654 Feb 28 18:18 initrd.buffalo.bak
-rw-r--r--  1 root root 2060867 Feb 28 18:18 uImage.buffalo.bak
drwxr-xr-x  3 root root    4096 Feb 28 18:18 dtbs
lrwxrwxrwx  1 root root      27 Feb 27 21:23 initrd.img -> initrd.img-4.19.0-8-marvell
lrwxrwxrwx  1 root root      27 Feb 27 21:23 initrd.img.old -> initrd.img-4.19.0-8-marvell
lrwxrwxrwx  1 root root      24 Feb 27 21:23 vmlinuz -> vmlinuz-4.19.0-8-marvell
lrwxrwxrwx  1 root root      24 Feb 27 21:23 vmlinuz.old -> vmlinuz-4.19.0-8-marvell
-rw-r--r--  1 root root 1643741 Jan 26 15:01 System.map-4.19.0-8-marvell
-rw-r--r--  1 root root  169818 Jan 26 15:01 config-4.19.0-8-marvell
-rw-r--r--  1 root root 2048576 Jan 26 15:01 vmlinuz-4.19.0-8-marvell

**Comment by 1000001101000** [comment] 2020-03-01 23:06
The goal is to overlay the /boot on sda4 with sda1 and then generate the files

mount /dev/sda4 /mnt
followed by
mount /dev/sda1 /mnt/boot/

should accomplish that.

**Comment by bcoff12** [comment] 2020-03-01 23:10
Ok....  That should have happened but I will try again.

**Comment by 1000001101000** [comment] 2020-03-01 23:16
Yeah, I would think it would have thrown an error if done out of order or something.

**Comment by bcoff12** [comment] 2020-03-01 23:17
Ok, update-initramfs exited without doing anything (I saw it doing things with the /boot on sda4:

root@debian:/# update-initramfs -u -v
Available versions:
Nothing to do, exiting.

**Comment by bcoff12** [comment] 2020-03-01 23:26
I can get you on this device tomorrow if that helps.

**Comment by 1000001101000** [comment] 2020-03-01 23:37
Doh! I missed a step in what I told you (or rather gave you instructions for a different scenario)

You either need to copy the files from the old /boot to the new /boot first or re-install the kernel package with the new /boot mounted.

This should work (from inside the chroot):
apt-get install --reinstall linux-image-$(uname -r)

**Comment by 1000001101000** [comment] 2020-03-02 00:38
Normally i’d recommend just re-doing the install but given how long this one took it seems worth trying to avoid that. At least until we can figure out if the disk is failing or not.

**Comment by bcoff12** [comment] 2020-03-02 13:11
Ok - after I followed your last instruction, the update-initramfs seemed to work and I rebooted but the device (DHCP) disappeared from the network.  Today I looked and it actually pulled a different address.  I am able to login to the Debian environment and su is working.

I have a busy morning but if you want me to make this internet accessible I can do that.

**Comment by 1000001101000** [comment] 2020-03-02 17:07
No rush on my side.

dhcp being different isn't surprising, something has changed about dhcp client ids in Buster which makes some DHCP servers treat them as different.

I think the next priority is to check out that drive. It should be as simple as installing smartmontools and checking for reloacted/pending sectors (or other issues I suppose).

 If that doesn't turn up anything we can come up with some other benchmarks to run.

**Comment by bcoff12** [comment] 2020-03-02 20:12
I tried to load smartmontools but ran into an error.

I have an image of the thing... I put it in my DMZ.

User is user

pass is destroyme for everything - you can change that if you get in...  I'll keep an eye on it...  if it gets hacked I'll shut it down....

**Comment by bcoff12** [comment] 2020-03-02 20:13
99.133.184.129:6502

**Comment by 1000001101000** [comment] 2020-03-02 21:10
got the info, deleted the comments

**Comment by 1000001101000** [comment] 2020-03-02 21:34
looks like that low-memory tweak is more important than I thought. Once I put that in place it installed without issue.

I changed the password out of paranoia someone else might try to connect, I can post the new one after you remove it from the DMZ if you like. I can also send a public key if we need to do it again. 

Looks like the drive is in bad shape:
5 Reallocated_Sector_Ct   0x0033   098   098   036    Pre-fail  Always       -       114
197 Current_Pending_Sector  0x0012   100   100   000    Old_age   Always       -       18
198 Offline_Uncorrectable   0x0010   100   100   000    Old_age   Offline      -       18

**Comment by bcoff12** [comment] 2020-03-02 21:43
Ok - I have an image of the device so I'm not worried about the drive being bad...  I can swap it out if necessary.

I can close the port to keep further login attempts at bay, but you will need to stay connected or else you won't be able to get back in.  I'll re-open it if you need me to.

I'm not worried about the device itself - I just want to make sure you can get any info you need.  The only reason I'm remotely worried about someone else being on there is they could use it for spamming or something else that would cause me grief!

**Comment by 1000001101000** [comment] 2020-03-02 21:56
Yeah, becoming part of a bot net is my worst nightmare. Do you want to leave it accessible for a little bit? I poked at a couple of things and could try a device-tree quick (which may make it fail to boot if it doesn't work)

**Comment by bcoff12** [comment] 2020-03-02 22:08
I'll leave it up as long as you need.

And I can restore it to Debian pretty quickly (I have a Clonezilla image)

Do whatever you need to do!

**Comment by 1000001101000** [comment] 2020-03-02 22:22
alright, I just rebooted it. Not sure if I'll see it come up or not.

**Comment by bcoff12** [comment] 2020-03-02 22:22
I think it is back up... hang on I'll open the port...

**Comment by 1000001101000** [comment] 2020-03-02 22:27
Looks like that worked just fine. I'll play around with that same tree with my installer on the lschlv2 and see if I can figure out why my installer never worked for you. most of the rest of the device tree work will need to wait until you are by the device to test leds/etc.

if you restore to a new drive you'll want to adjust the tmpfs with:
echo "tmpfs /run tmpfs nosuid,noexec,size=26M,nr_inodes=4096 0  0" >> /etc/fstab
mount -o remount tmpfs

**Comment by bcoff12** [comment] 2020-03-02 22:28
Ok thanks!  Closing port...

**Comment by 1000001101000** [comment] 2020-03-02 22:30
I changed user to password1 in case you need it

**Comment by bcoff12** [comment] 2020-03-02 22:34
Got it thank you

**Comment by bcoff12** [comment] 2020-03-03 20:21
Restoring to a 2TB drive with a billion hours on it but I think it is still working OK.  I'll put it back online with your password and mine for root.  I'll advise when it is online.

**Comment by bcoff12** [comment] 2020-03-03 20:39
Ok should be accessible and I updated fstab with the information you provided.

**Comment by 1000001101000** [comment] 2020-03-03 21:40
I was able to connect, this drive is in much better shape. 

When I get some time I'll get the custom dtb on there and work on finishing it. Once that's ready I'll run through my installer with it on the lschlv2 and assuming that works try it on the ls-xl. I'm hoping we'll have much better performance this time.

**Comment by 1000001101000** [comment] 2020-03-04 03:40
made some dtb progress, let me know when you'll have a chance to test out the led

**Comment by bcoff12** [comment] 2020-03-05 13:59
I'm really busy but the device is right in front of me and I can see the one? LED.  I can leave this open and hopefully give you the information you need.

**Comment by 1000001101000** [comment] 2020-03-05 14:05
Sounds good. I’ll try to set it to blinking when I get a chance so we can confirm that’s working.

**Comment by bcoff12** [comment] 2020-03-05 15:01
Ok... 10AM solid blue.

**Comment by 1000001101000** [comment] 2020-03-05 15:09
i just tried switching it off, is it off?

**Comment by bcoff12** [comment] 2020-03-05 15:17
Off

**Comment by 1000001101000** [comment] 2020-03-05 15:43
nice.

**Comment by 1000001101000** [comment] 2020-03-09 20:19
sorry, haven't had a chance to work on this for a few days. Hoping to have an installer to test about an hour after I get a chance to look at it again.

**Comment by bcoff12** [comment] 2020-03-10 20:07
No problem...  I've been very busy.  It is shutdown right now but I can bring it back up anytime...

**Comment by 1000001101000** [comment] 2020-03-21 16:05
I haven't forgotten about this, though it will be a few days before I get back to it.

**Comment by bcoff12** [comment] 2020-03-24 14:50
Take your time.  I am working from home and the device is on my desk.  I have someone there I can have plug it in if we want to continue.  I am in no hurry at all, but I think it will be great to have support for this device for everyone.

**Comment by 1000001101000** [comment] 2020-04-06 01:53
Coincidently I’ve been contacted by someone trying to install on a ls-chlv2, they ran into something I hadn’t noticed before. The installer operates in something called “low memory mode”.  When I tried it took a couple of tries to get far enough to activate swap and continue.

This is might be why my version of the installer fails on these devices, i’m still looking into it.

Did it go into “low memory mode” when you ran your install?

**Comment by bcoff12** [comment] 2020-04-06 11:08
I believe it did.

I'm going from memory, but one thing that helped a lot was creating a swap partition using a PC and then activating it before running through the install.

**Comment by 1000001101000** [comment] 2020-04-06 14:25
When I get some time I'm going to take a look at adding some code to try to activate swap earlier in the install process (like before it even starts the ssh server). I think that should be doable for non-raid devices at least.

though first I have to figure out how to get my installer to load on these devices.

**Comment by 1000001101000** [comment] 2020-05-19 18:16
I ended up figuring out the issues related to the debian installer and devices with 64mb of ram. I've now got a separate "lowmem" version of the installer published which activates swap before starting the ssh server to prevent early crashes. As you noticed previously the install process ends up taking many hours to complete.

I don't see many options for speeding things up, but the devices seem to run fine once the install completes.

**Comment by bcoff12** [comment] 2020-05-19 18:33
That's a minor issue versus not being able to use these.  Thank you so much!

**Comment by 1000001101000** [comment] 2020-05-28 03:32
After spending entirely too much effort developing the low memory installer (though learning a lot) another user with an ls-chlv2 was having trouble getting through the install and wasn't happy with how long it was taking. They asked me for a disk image they could load. This got me thinking about generating disk images as an alternative to the installer for some circumstances. before I knew it I had written a script and tested it against a few devices.  

I've committed it to the repo and put some setup instructions in the other thread:
https://github.com/1000001101000/Debian_on_Buffalo/issues/38#issuecomment-635072289

for the ls-xl you would want the change the "machine" variable to "Buffalo Linkstation LS-XL". Let me know if you get a chance to try it. I'm thinking of making a few more improvements and recommending it for more devices/situations.

**Comment by 1000001101000** [comment] 2020-08-29 14:17
Is there anything else you want me to look at for this?

I'm looking to close out some issues.

**Comment by bcoff12** [comment] 2020-08-31 19:16
Can be closed.  A++++.  Thank you!

**Closed** 2020-08-31 19:32 UTC
